name: Rudderstack-tracking-plan-backend-deployment-pipeline

on:
  push:
    branches: [ "development" ]

jobs:

  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Running deployment...
      run:  sudo sh setup.sh
